// File generated by FlutterFire CLI.
// Converted manually from GoogleService-Info.plist and google-services.json
import 'dart:io';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (Platform.isIOS) {
      return ios;
    }
    if (Platform.isAndroid) {
      return android;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdc0JBsaWulfrmRrn5JeKvYasUWBVk5W0',
    appId: '1:168360567831:ios:61ef31962ff4fb0822e852',
    messagingSenderId: '168360567831',
    projectId: 'upper-room-22dbb',
    storageBucket: 'upper-room-22dbb.firebasestorage.app',
    iosClientId: '168360567831-rvnabj5a0pn2e6m5j6q0a0a0a0a0a0a0.apps.googleusercontent.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDekEay-YkQMajPF-skIWKbj7WPAMC_RAM',
    appId: '1:168360567831:android:cc9a128d03a451ad22e852',
    messagingSenderId: '168360567831',
    projectId: 'upper-room-22dbb',
    storageBucket: 'upper-room-22dbb.firebasestorage.app',
  );
}
